version: '3.10'

services:
  database:
    container_name: database
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
    # expose:
    #   - 8123
    networks:
      customnetwork:
        ipv4_address: 172.25.0.2
    ulimits:
      nofile: 262144
    environment:
      CLICKHOUSE_DB: default
      # CLICKHOUSECONFIG: default_session_timeout=120
      CLICKHOUSE_USER:  utain 
      CLICKHOUSE_PASSWORD: 3244
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - ./database/config.xml:/etc/clickhouse-server/config.xml
      # - ./database/users.xml:/etc/clickhouse-server/users.xml
    # command: hostname -i

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    # networks:
    #   - customnetwork
    environment:
      - DB_USER=utain
      - DB_HOST=172.25.0.2
      - DB_PASS=3244
    volumes:
      - .:/app
    restart: on-failure
    depends_on:
      - database
    #     condition: service_healthy

networks:
  customnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16