name: ci

on:
  push:
    branches:
      - "main"

jobs:     
  build:
    runs-on: ubuntu-latest      
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.1.0
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
      #     build-args: |
      #       DB_HOST=192.168.65.4
      #       DB_USER=utain
      #       DB_PASS = 3244 
      -
        name: Build docker
        run: docker-compose build
      -
        name: Start docker
        shell: bash
        run: docker-compose up -d
      -
        name: Run docker
        shell: bash
        run: docker-compose run app 
      - 
        name: Stop docker
        shell: bash
        run: docker-compose down
